
/**
 * FreeIMU calibration header. Automatically generated by octave AccMagnCalib.m.
 * Do not edit manually unless you know what you are doing.
*/


#define CALIBRATION_H

const int acc_off_x = 135;
const int acc_off_y = -87;
const int acc_off_z = 1217;
const float acc_scale_x = 8023.811582;
const float acc_scale_y = 8357.684458;
const float acc_scale_z = 8486.858537;

const int magn_off_x = 71;
const int magn_off_y = -21;
const int magn_off_z = 72;
const float magn_scale_x = 531.707255;
const float magn_scale_y = 600.926616;
const float magn_scale_z = 576.828209;
