
/**
 * FreeIMU calibration header. Automatically generated by FreeIMU_GUI.
 * Do not edit manually unless you know what you are doing.
*/


#define CALIBRATION_H

const int acc_off_x = -576;
const int acc_off_y = 121;
const int acc_off_z = -137;
const float acc_scale_x = 16631.522970;
const float acc_scale_y = 16524.320241;
const float acc_scale_z = 16512.024899;

const int magn_off_x = 9;
const int magn_off_y = -223;
const int magn_off_z = -70;
const float magn_scale_x = 430.335177;
const float magn_scale_y = 866.251333;
const float magn_scale_z = 524.871516;
