
/**
 * FreeIMU calibration header. Automatically generated by FreeIMU_GUI.
 * Do not edit manually unless you know what you are doing.
*/


#define CALIBRATION_H

const int acc_off_x = -1600;
const int acc_off_y = -530;
const int acc_off_z = -767;
const float acc_scale_x = 16329.706249;
const float acc_scale_y = 16429.389899;
const float acc_scale_z = 16930.394579;

const int magn_off_x = -7;
const int magn_off_y = -80;
const int magn_off_z = -72;
const float magn_scale_x = 530.586710;
const float magn_scale_y = 484.551238;
const float magn_scale_z = 428.687197;
