
/**
 * FreeIMU calibration header. Automatically generated by FreeIMU_GUI.
 * Do not edit manually unless you know what you are doing.
*/


#define CALIBRATION_H

const int acc_off_x = 426;
const int acc_off_y = -141;
const int acc_off_z = -540;
const float acc_scale_x = 16255.420145;
const float acc_scale_y = 16389.952315;
const float acc_scale_z = 16598.537030;

const int magn_off_x = 222;
const int magn_off_y = -190;
const int magn_off_z = -67;
const float magn_scale_x = 488.787511;
const float magn_scale_y = 513.264462;
const float magn_scale_z = 434.896123;
