
/**
 * FreeIMU calibration header. Automatically generated by FreeIMU_GUI.
 * Do not edit manually unless you know what you are doing.
*/


#define CALIBRATION_H

const int acc_off_x = -2369;
const int acc_off_y = -361;
const int acc_off_z = -942;
const float acc_scale_x = 16258.6537173;
const float acc_scale_y = 16472.8788037;
const float acc_scale_z = 16981.855657;

const int magn_off_x = 0;
const int magn_off_y = 0;
const int magn_off_z = 0;
const float magn_scale_x = 1;
const float magn_scale_y = 1;
const float magn_scale_z = 1;
