
/**
 * FreeIMU calibration header. Automatically generated by FreeIMU_GUI.
 * Do not edit manually unless you know what you are doing.
*/


#define CALIBRATION_H

const int acc_off_x = -2210;
const int acc_off_y = -440;
const int acc_off_z = -923;
const float acc_scale_x = 16401.692173;
const float acc_scale_y = 16441.189898;
const float acc_scale_z = 16920.251484;

const int magn_off_x = 44;
const int magn_off_y = -77;
const int magn_off_z = -78;
const float magn_scale_x = 512.323439;
const float magn_scale_y = 466.957208;
const float magn_scale_z = 414.812217;
