
/**
 * FreeIMU calibration header. Automatically generated by FreeIMU_GUI.
 * Do not edit manually unless you know what you are doing.
*/


#define CALIBRATION_H

const int acc_off_x = 262;
const int acc_off_y = -369;
const int acc_off_z = 396;
const float acc_scale_x = 7949.636995;
const float acc_scale_y = 8330.990388;
const float acc_scale_z = 8115.774341;

const int magn_off_x = 117;
const int magn_off_y = -117;
const int magn_off_z = 623;
const float magn_scale_x = 443.990729;
const float magn_scale_y = 437.307466;
const float magn_scale_z = 426.042986;
