
/**
 * FreeIMU calibration header. Automatically generated by FreeIMU_GUI.
 * Do not edit manually unless you know what you are doing.
*/


#define CALIBRATION_H

const int acc_off_x = -58;
const int acc_off_y = 54;
const int acc_off_z = 5;
const float acc_scale_x = 16352.340827;
const float acc_scale_y = 16460.673595;
const float acc_scale_z = 16552.619086;

const int magn_off_x = 67;
const int magn_off_y = -141;
const int magn_off_z = 8;
const float magn_scale_x = 267.261116;
const float magn_scale_y = 254.536389;
const float magn_scale_z = 273.278292;
