
/**
 * FreeIMU calibration header. Automatically generated by FreeIMU_GUI.
 * Do not edit manually unless you know what you are doing.
*/


#define CALIBRATION_H

const int acc_off_x = -15;
const int acc_off_y = -7;
const int acc_off_z = -12;
const float acc_scale_x = 252.870682;
const float acc_scale_y = 259.785941;
const float acc_scale_z = 249.538992;

const int magn_off_x = 17;
const int magn_off_y = -92;
const int magn_off_z = 45;
const float magn_scale_x = 513.763319;
const float magn_scale_y = 491.982172;
const float magn_scale_z = 483.095061;
