
/**
 * FreeIMU calibration header. Automatically generated by FreeIMU_GUI.
 * Do not edit manually unless you know what you are doing.
*/


#define CALIBRATION_H

const int acc_off_x = 105;
const int acc_off_y = 133;
const int acc_off_z = -509;
const float acc_scale_x = 16249.525126;
const float acc_scale_y = 16499.994927;
const float acc_scale_z = 16540.955523;

const int magn_off_x = 18;
const int magn_off_y = -113;
const int magn_off_z = 54;
const float magn_scale_x = 551.134309;
const float magn_scale_y = 512.453589;
const float magn_scale_z = 506.678419;
