
/**
 * FreeIMU calibration header. Automatically generated by FreeIMU_GUI.
 * Do not edit manually unless you know what you are doing.
*/


#define CALIBRATION_H

const int acc_off_x = 175;
const int acc_off_y = 340;
const int acc_off_z = 1579;
const float acc_scale_x = 15978.730935;
const float acc_scale_y = 16075.221404;
const float acc_scale_z = 16671.035043;

const int magn_off_x = 648;
const int magn_off_y = 32;
const int magn_off_z = 1304;
const float magn_scale_x = 5826.984610;
const float magn_scale_y = 6045.323527;
const float magn_scale_z = 5565.694163;
