
/**
 * FreeIMU calibration header. Automatically generated by FreeIMU_GUI.
 * Do not edit manually unless you know what you are doing.
*/


#define CALIBRATION_H

const int acc_off_x = -12;
const int acc_off_y = -6;
const int acc_off_z = -17;
const float acc_scale_x = 252.819758;
const float acc_scale_y = 260.088845;
const float acc_scale_z = 249.585607;

const int magn_off_x = -67;
const int magn_off_y = 7;
const int magn_off_z = 53;
const float magn_scale_x = 507.274413;
const float magn_scale_y = 487.617013;
const float magn_scale_z = 480.880601;
