/**
 * FreeIMU calibration header. Automatically generated by octave AccMagnCalib.m.
 * Do not edit manually unless you know what you are doing.
*/

#define CALIBRATION_H

const int acc_off_x = 87.65701;
const int acc_off_y = -25.67070;
const int acc_off_z = -967.5962;
const float acc_scale_x = 16290.045625;
const float acc_scale_y = 16611.237118;
const float acc_scale_z = 16670.381598;


const int magn_off_x = 0;
const int magn_off_y = 0;
const int magn_off_z = 0;
const float magn_scale_x = 1;
const float magn_scale_y = 1;
const float magn_scale_z = 1;
