
/**
 * FreeIMU calibration header. Automatically generated by FreeIMU_GUI.
 * Do not edit manually unless you know what you are doing.
*/


#define CALIBRATION_H

const int acc_off_x = 10;
const int acc_off_y = -114;
const int acc_off_z = -165;
const float acc_scale_x = 16304.441551;
const float acc_scale_y = 16378.489946;
const float acc_scale_z = 16360.595654;

const int magn_off_x = -28;
const int magn_off_y = -15;
const int magn_off_z = 21;
const float magn_scale_x = 134.902723;
const float magn_scale_y = 138.669683;
const float magn_scale_z = 128.622510;
