
/**
 * FreeIMU calibration header. Automatically generated by FreeIMU_GUI.
 * Do not edit manually unless you know what you are doing.
*/


#define CALIBRATION_H

const int acc_off_x = -241;
const int acc_off_y = -10;
const int acc_off_z = -473;
const float acc_scale_x = 16366.101527;
const float acc_scale_y = 16468.300051;
const float acc_scale_z = 16592.721927;

const int magn_off_x = 5;
const int magn_off_y = 322;
const int magn_off_z = -111;
const float magn_scale_x = 249.601000;
const float magn_scale_y = 255.215175;
const float magn_scale_z = 266.757685;
