
/**
 * FreeIMU calibration header. Automatically generated by FreeIMU_GUI.
 * Do not edit manually unless you know what you are doing.
*/


#define CALIBRATION_H

const int acc_off_x = 14;
const int acc_off_y = 6;
const int acc_off_z = -17;
const float acc_scale_x = 256.198220;
const float acc_scale_y = 265.974977;
const float acc_scale_z = 258.631278;

const int magn_off_x = 99;
const int magn_off_y = -95;
const int magn_off_z = 81;
const float magn_scale_x = 579.202452;
const float magn_scale_y = 509.184578;
const float magn_scale_z = 457.017329;
