
/**
 * FreeIMU calibration header. Automatically generated by FreeIMU_GUI.
 * Do not edit manually unless you know what you are doing.
*/


#define CALIBRATION_H

const int acc_off_x = 163;
const int acc_off_y = 119;
const int acc_off_z = -622;
const float acc_scale_x = 16387.035965;
const float acc_scale_y = 16493.176991;
const float acc_scale_z = 16517.294625;

const int magn_off_x = 27;
const int magn_off_y = -88;
const int magn_off_z = 47;
const float magn_scale_x = 587.938843;
const float magn_scale_y = 569.650149;
const float magn_scale_z = 539.296833;
