
/**
 * FreeIMU calibration header. Automatically generated by FreeIMU_GUI.
 * Do not edit manually unless you know what you are doing.
*/


#define CALIBRATION_H

const int acc_off_x = -62;
const int acc_off_y = 27;
const int acc_off_z = 45;
const float acc_scale_x = 16345.045131;
const float acc_scale_y = 16448.799054;
const float acc_scale_z = 16537.291158;

const int magn_off_x = 82;
const int magn_off_y = -16;
const int magn_off_z = 101;
const float magn_scale_x = 256.692864;
const float magn_scale_y = 259.615633;
const float magn_scale_z = 269.169416;
