/**
 * FreeIMU calibration header. Automatically generated by octave AccMagnCalib.m.
 * Do not edit manually unless you know what you are doing.
*/

const int acc_off_x = 9.452150;
const int acc_off_y = -0.4503506;
const int acc_off_z = -23.21088e+001;
const float acc_scale_x = 256.212542;
const float acc_scale_y = 261.625419;
const float acc_scale_z = 258.109461;


const int magn_off_x = 76.81962;
const int magn_off_y = -117.9775;
const int magn_off_z = 80.72863;
const float magn_scale_x = 582.505989;
const float magn_scale_y = 510.861999;
const float magn_scale_z = 463.431172;
