
/**
 * FreeIMU calibration header. Automatically generated by FreeIMU_GUI.
 * Do not edit manually unless you know what you are doing.
*/


#define CALIBRATION_H

const int acc_off_x = 286;
const int acc_off_y = -330;
const int acc_off_z = 434;
const float acc_scale_x = 8110.047089;
const float acc_scale_y = 8215.780341;
const float acc_scale_z = 8038.271324;

const int magn_off_x = 263;
const int magn_off_y = -25;
const int magn_off_z = 602;
const float magn_scale_x = 437.323021;
const float magn_scale_y = 432.640532;
const float magn_scale_z = 426.850503;
