
/**
 * FreeIMU calibration header. Automatically generated by FreeIMU_GUI.
 * Do not edit manually unless you know what you are doing.
*/


#define CALIBRATION_H

const int acc_off_x = -13;
const int acc_off_y = -7;
const int acc_off_z = -14;
const float acc_scale_x = 252.551548;
const float acc_scale_y = 260.244190;
const float acc_scale_z = 250.523972;

const int magn_off_x = 8;
const int magn_off_y = -85;
const int magn_off_z = 38;
const float magn_scale_x = 525.072503;
const float magn_scale_y = 492.829055;
const float magn_scale_z = 489.613078;
