# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'freeimu_cal.ui'
#
# Created: Mon Dec 17 17:22:26 2012
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!
from PyQt5 import QtWidgets, QtGui, QtCore, QtWidgets
from PyQt5.QtCore import *
from PyQt5.QtGui import *
from PyQt5.QtWidgets import *

try:
    _fromUtf8 = lambda s: s
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    #_encoding = QtWidgets.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        #return QtWidgets.QApplication.translate(context, text, disambig, _encoding)
        return QtWidgets.QApplication.translate(context, text, disambig)
except AttributeError:
    def _translate(context, text, disambig):
        return QtWidgets.QApplication.translate(context, text, disambig)

class Ui_FreeIMUCal(object):
    def setupUi(self, FreeIMUCal):
        FreeIMUCal.setObjectName(_fromUtf8("FreeIMUCal"))
        FreeIMUCal.resize(800, 680)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(FreeIMUCal.sizePolicy().hasHeightForWidth())
        FreeIMUCal.setSizePolicy(sizePolicy)
        FreeIMUCal.setMinimumSize(QtCore.QSize(800, 600))
        FreeIMUCal.setMaximumSize(QtCore.QSize(800, 680))
        FreeIMUCal.setDocumentMode(False)
        self.centralwidget = QtWidgets.QWidget(FreeIMUCal)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(10, 20, 791, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 801, 25))
        self.gridLayoutWidget.setObjectName(_fromUtf8("gridLayoutWidget"))
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        #self.gridLayout.setContentsMargins(0,0,0,0)
        self.gridLayout.setContentsMargins(0,0,0,0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.line_2 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.gridLayout.addWidget(self.line_2, 0, 4, 1, 1)
        self.samplingToggleButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.samplingToggleButton.setEnabled(False)
        self.samplingToggleButton.setAutoDefault(False)
        self.samplingToggleButton.setDefault(False)
        self.samplingToggleButton.setFlat(False)
        self.samplingToggleButton.setObjectName(_fromUtf8("samplingToggleButton"))
        self.gridLayout.addWidget(self.samplingToggleButton, 0, 7, 1, 1)
        self.serialPortEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.serialPortEdit.setObjectName(_fromUtf8("serialPortEdit"))
        self.gridLayout.addWidget(self.serialPortEdit, 0, 1, 1, 1)
        self.calibrateButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.calibrateButton.setEnabled(False)
        self.calibrateButton.setObjectName(_fromUtf8("calibrateButton"))
        self.gridLayout.addWidget(self.calibrateButton, 0, 9, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.setBaudRateComboBox = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.setBaudRateComboBox.setEnabled(True)
        self.setBaudRateComboBox.setObjectName(_fromUtf8("setBaudRateComboBox"))
        self.setBaudRateComboBox.addItem(_fromUtf8(""))
        self.calAlgorithmComboBox = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.calAlgorithmComboBox.setEnabled(False)
        self.calAlgorithmComboBox.setObjectName(_fromUtf8("calAlgorithmComboBox"))
        self.calAlgorithmComboBox.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.setBaudRateComboBox, 0, 3, 1, 1)
        self.gridLayout.addWidget(self.calAlgorithmComboBox, 0, 8, 1, 1)
        self.connectButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.connectButton.setObjectName(_fromUtf8("connectButton"))
        self.gridLayout.addWidget(self.connectButton, 0, 5, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 6, 1, 1)
        self.serialProtocol = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.serialProtocol.setEnabled(True)
        self.serialProtocol.setObjectName(_fromUtf8("serialProtocol"))
        self.serialProtocol.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.serialProtocol, 0, 2, 1, 1)
		
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 30, 801, 631))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.uncalibratedTab = QtWidgets.QWidget()
        self.uncalibratedTab.setObjectName(_fromUtf8("uncalibratedTab"))
        self.gridLayoutWidget_4 = QtWidgets.QWidget(self.uncalibratedTab)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(0, 10, 791, 588))
        self.gridLayoutWidget_4.setObjectName(_fromUtf8("gridLayoutWidget_4"))
        self.gridLayout_4 = QtWidgets.QGridLayout(self.gridLayoutWidget_4)
        self.gridLayout_4.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        #self.gridLayout_4.setContentsMargins(0,0,0,0)
        self.gridLayout_4.setContentsMargins(0,0,0,0)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_5.addWidget(self.label_2, 0, 1, 1, 1)
        self.accYZ = PlotWidget(self.gridLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.accYZ.sizePolicy().hasHeightForWidth())
        self.accYZ.setSizePolicy(sizePolicy)
        self.accYZ.setObjectName(_fromUtf8("accYZ"))
        self.gridLayout_5.addWidget(self.accYZ, 1, 0, 1, 1)
        self.accZX = PlotWidget(self.gridLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.accZX.sizePolicy().hasHeightForWidth())
        self.accZX.setSizePolicy(sizePolicy)
        self.accZX.setObjectName(_fromUtf8("accZX"))
        self.gridLayout_5.addWidget(self.accZX, 1, 1, 1, 1)
        self.accXY = PlotWidget(self.gridLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.accXY.sizePolicy().hasHeightForWidth())
        self.accXY.setSizePolicy(sizePolicy)
        self.accXY.setObjectName(_fromUtf8("accXY"))
        self.gridLayout_5.addWidget(self.accXY, 0, 0, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_5, 1, 0, 1, 1)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.magnXY = PlotWidget(self.gridLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.magnXY.sizePolicy().hasHeightForWidth())
        self.magnXY.setSizePolicy(sizePolicy)
        self.magnXY.setObjectName(_fromUtf8("magnXY"))
        self.gridLayout_3.addWidget(self.magnXY, 0, 0, 1, 1)
        self.magnYZ = PlotWidget(self.gridLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.magnYZ.sizePolicy().hasHeightForWidth())
        self.magnYZ.setSizePolicy(sizePolicy)
        self.magnYZ.setObjectName(_fromUtf8("magnYZ"))
        self.gridLayout_3.addWidget(self.magnYZ, 1, 0, 1, 1)
        self.magnZX = PlotWidget(self.gridLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.magnZX.sizePolicy().hasHeightForWidth())
        self.magnZX.setSizePolicy(sizePolicy)
        self.magnZX.setObjectName(_fromUtf8("magnZX"))
        self.gridLayout_3.addWidget(self.magnZX, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_3.addWidget(self.label_3, 0, 1, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_3, 1, 2, 1, 1)
        self.magn3D = GLViewWidget(self.gridLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.magn3D.sizePolicy().hasHeightForWidth())
        self.magn3D.setSizePolicy(sizePolicy)
        self.magn3D.setObjectName(_fromUtf8("magn3D"))
        self.gridLayout_4.addWidget(self.magn3D, 0, 2, 1, 1)
        self.acc3D = GLViewWidget(self.gridLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.acc3D.sizePolicy().hasHeightForWidth())
        self.acc3D.setSizePolicy(sizePolicy)
        self.acc3D.setObjectName(_fromUtf8("acc3D"))
        self.gridLayout_4.addWidget(self.acc3D, 0, 0, 1, 1)
        self.line_3 = QtWidgets.QFrame(self.gridLayoutWidget_4)
        self.line_3.setLineWidth(1)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.gridLayout_4.addWidget(self.line_3, 1, 1, 1, 1)
        self.tabWidget.addTab(self.uncalibratedTab, _fromUtf8(""))
        self.calibratedTab = QtWidgets.QWidget()
        self.calibratedTab.setObjectName(_fromUtf8("calibratedTab"))
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.calibratedTab)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 380, 791, 181))
        self.horizontalLayoutWidget.setObjectName(_fromUtf8("horizontalLayoutWidget"))
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        #self.horizontalLayout.setContentsMargins(0,0,0,0)
        self.horizontalLayout.setContentsMargins(0,0,0,0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.groupBox = QtWidgets.QGroupBox(self.horizontalLayoutWidget)
        self.groupBox.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupBox.setFlat(False)
        self.groupBox.setCheckable(False)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.layoutWidget = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 20, 381, 154))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.formLayout_3 = QtWidgets.QFormLayout(self.layoutWidget)
        self.formLayout_3.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.formLayout_3.setFieldGrowthPolicy(QtWidgets.QFormLayout.ExpandingFieldsGrow)
        self.formLayout_3.setLabelAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.formLayout_3.setContentsMargins(0,0,0,0)
        self.formLayout_3.setObjectName(_fromUtf8("formLayout_3"))
        self.label_14 = QtWidgets.QLabel(self.layoutWidget)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_14)
        self.calRes_acc_OSx = QtWidgets.QLineEdit(self.layoutWidget)
        self.calRes_acc_OSx.setObjectName(_fromUtf8("calRes_acc_OSx"))
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.calRes_acc_OSx)
        self.label_15 = QtWidgets.QLabel(self.layoutWidget)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_15)
        self.calRes_acc_OSy = QtWidgets.QLineEdit(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.calRes_acc_OSy.sizePolicy().hasHeightForWidth())
        self.calRes_acc_OSy.setSizePolicy(sizePolicy)
        self.calRes_acc_OSy.setObjectName(_fromUtf8("calRes_acc_OSy"))
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.calRes_acc_OSy)
        self.label_16 = QtWidgets.QLabel(self.layoutWidget)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_16)
        self.calRes_acc_OSz = QtWidgets.QLineEdit(self.layoutWidget)
        self.calRes_acc_OSz.setObjectName(_fromUtf8("calRes_acc_OSz"))
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.calRes_acc_OSz)
        self.label_17 = QtWidgets.QLabel(self.layoutWidget)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_17)
        self.calRes_acc_SCx = QtWidgets.QLineEdit(self.layoutWidget)
        self.calRes_acc_SCx.setObjectName(_fromUtf8("calRes_acc_SCx"))
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.calRes_acc_SCx)
        self.label_18 = QtWidgets.QLabel(self.layoutWidget)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.formLayout_3.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_18)
        self.calRes_acc_SCy = QtWidgets.QLineEdit(self.layoutWidget)
        self.calRes_acc_SCy.setObjectName(_fromUtf8("calRes_acc_SCy"))
        self.formLayout_3.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.calRes_acc_SCy)
        self.label_19 = QtWidgets.QLabel(self.layoutWidget)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.formLayout_3.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_19)
        self.calRes_acc_SCz = QtWidgets.QLineEdit(self.layoutWidget)
        self.calRes_acc_SCz.setObjectName(_fromUtf8("calRes_acc_SCz"))
        self.formLayout_3.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.calRes_acc_SCz)
        self.horizontalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.horizontalLayoutWidget)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.layoutWidget_2 = QtWidgets.QWidget(self.groupBox_2)
        self.layoutWidget_2.setGeometry(QtCore.QRect(10, 20, 381, 154))
        self.layoutWidget_2.setObjectName(_fromUtf8("layoutWidget_2"))
        self.formLayout_5 = QtWidgets.QFormLayout(self.layoutWidget_2)
        self.formLayout_5.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.formLayout_5.setFieldGrowthPolicy(QtWidgets.QFormLayout.ExpandingFieldsGrow)
        self.formLayout_5.setLabelAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.formLayout_5.setContentsMargins(0,0,0,0)
        self.formLayout_5.setObjectName(_fromUtf8("formLayout_5"))
        self.label_27 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_27)
        self.calRes_magn_OSx = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.calRes_magn_OSx.setObjectName(_fromUtf8("calRes_magn_OSx"))
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.calRes_magn_OSx)
        self.label_28 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_28)
        self.calRes_magn_OSy = QtWidgets.QLineEdit(self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.calRes_magn_OSy.sizePolicy().hasHeightForWidth())
        self.calRes_magn_OSy.setSizePolicy(sizePolicy)
        self.calRes_magn_OSy.setObjectName(_fromUtf8("calRes_magn_OSy"))
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.calRes_magn_OSy)
        self.label_29 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.formLayout_5.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_29)
        self.calRes_magn_OSz = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.calRes_magn_OSz.setObjectName(_fromUtf8("calRes_magn_OSz"))
        self.formLayout_5.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.calRes_magn_OSz)
        self.label_30 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.formLayout_5.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_30)
        self.calRes_magn_SCx = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.calRes_magn_SCx.setObjectName(_fromUtf8("calRes_magn_SCx"))
        self.formLayout_5.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.calRes_magn_SCx)
        self.label_31 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.formLayout_5.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_31)
        self.calRes_magn_SCy = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.calRes_magn_SCy.setObjectName(_fromUtf8("calRes_magn_SCy"))
        self.formLayout_5.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.calRes_magn_SCy)
        self.label_32 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.formLayout_5.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_32)
        self.calRes_magn_SCz = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.calRes_magn_SCz.setObjectName(_fromUtf8("calRes_magn_SCz"))
        self.formLayout_5.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.calRes_magn_SCz)
        self.horizontalLayout.addWidget(self.groupBox_2)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.calibratedTab)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(488, 560, 301, 31))
        self.horizontalLayoutWidget_2.setObjectName(_fromUtf8("horizontalLayoutWidget_2"))
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0,0,0,0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.saveCalibrationEEPROMButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.saveCalibrationEEPROMButton.setEnabled(False)
        self.saveCalibrationEEPROMButton.setObjectName(_fromUtf8("saveCalibrationEEPROMButton"))
        self.horizontalLayout_2.addWidget(self.saveCalibrationEEPROMButton)
        self.saveCalibrationHeaderButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.saveCalibrationHeaderButton.setEnabled(False)
        self.saveCalibrationHeaderButton.setObjectName(_fromUtf8("saveCalibrationHeaderButton"))
        self.horizontalLayout_2.addWidget(self.saveCalibrationHeaderButton)
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.calibratedTab)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(0, 0, 791, 381))
        self.horizontalLayoutWidget_3.setObjectName(_fromUtf8("horizontalLayoutWidget_3"))
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0,0,0,0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.tabWidget_2 = QtWidgets.QTabWidget(self.horizontalLayoutWidget_3)
        self.tabWidget_2.setTabPosition(QtWidgets.QTabWidget.South)
        self.tabWidget_2.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget_2.setUsesScrollButtons(True)
        self.tabWidget_2.setDocumentMode(False)
        self.tabWidget_2.setTabsClosable(False)
        self.tabWidget_2.setMovable(False)
        self.tabWidget_2.setObjectName(_fromUtf8("tabWidget_2"))
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.accXY_cal = PlotWidget(self.tab)
        self.accXY_cal.setGeometry(QtCore.QRect(0, 0, 781, 351))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.accXY_cal.sizePolicy().hasHeightForWidth())
        self.accXY_cal.setSizePolicy(sizePolicy)
        self.accXY_cal.setObjectName(_fromUtf8("accXY_cal"))
        self.tabWidget_2.addTab(self.tab, _fromUtf8(""))
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.accYZ_cal = PlotWidget(self.tab_4)
        self.accYZ_cal.setGeometry(QtCore.QRect(0, 0, 781, 351))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.accYZ_cal.sizePolicy().hasHeightForWidth())
        self.accYZ_cal.setSizePolicy(sizePolicy)
        self.accYZ_cal.setObjectName(_fromUtf8("accYZ_cal"))
        self.tabWidget_2.addTab(self.tab_4, _fromUtf8(""))
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.accZX_cal = PlotWidget(self.tab_3)
        self.accZX_cal.setGeometry(QtCore.QRect(0, 0, 781, 351))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.accZX_cal.sizePolicy().hasHeightForWidth())
        self.accZX_cal.setSizePolicy(sizePolicy)
        self.accZX_cal.setObjectName(_fromUtf8("accZX_cal"))
        self.tabWidget_2.addTab(self.tab_3, _fromUtf8(""))
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName(_fromUtf8("tab_7"))
        self.acc3D_cal = GLViewWidget(self.tab_7)
        self.acc3D_cal.setGeometry(QtCore.QRect(0, 0, 389, 351))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.acc3D_cal.sizePolicy().hasHeightForWidth())
        self.acc3D_cal.setSizePolicy(sizePolicy)
        self.acc3D_cal.setObjectName(_fromUtf8("acc3D_cal"))
        self.tabWidget_2.addTab(self.tab_7, _fromUtf8(""))
        self.horizontalLayout_3.addWidget(self.tabWidget_2)
        self.tabWidget_3 = QtWidgets.QTabWidget(self.horizontalLayoutWidget_3)
        self.tabWidget_3.setTabPosition(QtWidgets.QTabWidget.South)
        self.tabWidget_3.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget_3.setUsesScrollButtons(True)
        self.tabWidget_3.setDocumentMode(False)
        self.tabWidget_3.setTabsClosable(False)
        self.tabWidget_3.setMovable(False)
        self.tabWidget_3.setObjectName(_fromUtf8("tabWidget_3"))
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.magnXY_cal = PlotWidget(self.tab_2)
        self.magnXY_cal.setGeometry(QtCore.QRect(0, 0, 781, 351))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.magnXY_cal.sizePolicy().hasHeightForWidth())
        self.magnXY_cal.setSizePolicy(sizePolicy)
        self.magnXY_cal.setObjectName(_fromUtf8("magnXY_cal"))
        self.tabWidget_3.addTab(self.tab_2, _fromUtf8(""))
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName(_fromUtf8("tab_5"))
        self.magnYZ_cal = PlotWidget(self.tab_5)
        self.magnYZ_cal.setGeometry(QtCore.QRect(0, 0, 781, 351))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.magnYZ_cal.sizePolicy().hasHeightForWidth())
        self.magnYZ_cal.setSizePolicy(sizePolicy)
        self.magnYZ_cal.setObjectName(_fromUtf8("magnYZ_cal"))
        self.tabWidget_3.addTab(self.tab_5, _fromUtf8(""))
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName(_fromUtf8("tab_6"))
        self.magnZX_cal = PlotWidget(self.tab_6)
        self.magnZX_cal.setGeometry(QtCore.QRect(0, 0, 781, 351))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.magnZX_cal.sizePolicy().hasHeightForWidth())
        self.magnZX_cal.setSizePolicy(sizePolicy)
        self.magnZX_cal.setObjectName(_fromUtf8("magnZX_cal"))
        self.tabWidget_3.addTab(self.tab_6, _fromUtf8(""))
        self.tab_8 = QtWidgets.QWidget()
        self.tab_8.setObjectName(_fromUtf8("tab_8"))
        self.magn3D_cal = GLViewWidget(self.tab_8)
        self.magn3D_cal.setGeometry(QtCore.QRect(0, 0, 389, 351))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.magn3D_cal.sizePolicy().hasHeightForWidth())
        self.magn3D_cal.setSizePolicy(sizePolicy)
        self.magn3D_cal.setObjectName(_fromUtf8("magn3D_cal"))
        self.tabWidget_3.addTab(self.tab_8, _fromUtf8(""))
        self.horizontalLayout_3.addWidget(self.tabWidget_3)
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(self.calibratedTab)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(0, 560, 161, 31))
        self.horizontalLayoutWidget_4.setObjectName(_fromUtf8("horizontalLayoutWidget_4"))
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_4.setContentsMargins(0,0,0,0)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.clearCalibrationEEPROMButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_4)
        self.clearCalibrationEEPROMButton.setEnabled(False)
        self.clearCalibrationEEPROMButton.setObjectName(_fromUtf8("clearCalibrationEEPROMButton"))
        self.horizontalLayout_4.addWidget(self.clearCalibrationEEPROMButton)
        self.tabWidget.addTab(self.calibratedTab, _fromUtf8(""))
        self.tab_9 = QtWidgets.QWidget()
        self.tab_9.setObjectName(_fromUtf8("tab_9"))
        self.label_4 = QtWidgets.QLabel(self.tab_9)
        self.label_4.setGeometry(QtCore.QRect(290, 270, 261, 16))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.tabWidget.addTab(self.tab_9, _fromUtf8(""))
        FreeIMUCal.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(FreeIMUCal)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        FreeIMUCal.setStatusBar(self.statusbar)

        self.retranslateUi(FreeIMUCal)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(0)
        self.tabWidget_3.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(FreeIMUCal)

    def retranslateUi(self, FreeIMUCal):
        FreeIMUCal.setWindowTitle(_translate("FreeIMUCal", "FreeIMU Calibration Application", None))
        self.samplingToggleButton.setToolTip(_translate("FreeIMUCal", "Toggle Start/Stop sampling of sensor data from the IMU", None))
        self.samplingToggleButton.setText(_translate("FreeIMUCal", "Start Sampling", None))
        self.calibrateButton.setToolTip(_translate("FreeIMUCal", "Run calibration algorithm over the data collected", None))
        self.calibrateButton.setText(_translate("FreeIMUCal", "Calibrate", None))
        self.label.setText(_translate("FreeIMUCal", "Serial Port:", None))
        self.setBaudRateComboBox.setToolTip(_translate("FreeIMUCal", "<html><head/><body><p>Baud rate to Connect to MCU</p></body></html>", None))
        self.setBaudRateComboBox.setItemText(0, _translate("FreeIMUCal", "BaudRate", None))
        self.setBaudRateComboBox.addItem(_fromUtf8("115200"))
        self.setBaudRateComboBox.addItem(_fromUtf8("57600"))		
        self.setBaudRateComboBox.addItem(_fromUtf8("38400"))		
        self.setBaudRateComboBox.addItem(_fromUtf8("19200"))
        self.setBaudRateComboBox.addItem(_fromUtf8("9600"))		
        self.calAlgorithmComboBox.setToolTip(_translate("FreeIMUCal", "<html><head/><body><p>Calibration Algorithm used.</p></body></html>", None))
        self.calAlgorithmComboBox.setItemText(0, _translate("FreeIMUCal", "Ellipsoid to Sphere", None))
        self.connectButton.setToolTip(_translate("FreeIMUCal", "Connect or Disconnect from the Arduino", None))
        self.connectButton.setText(_translate("FreeIMUCal", "Connect", None))
        self.serialProtocol.setToolTip(_translate("FreeIMUCal", "Serial Protocol to Communicate with IMU", None))
        self.serialProtocol.setItemText(0, _translate("FreeIMUCal", "FreeIMU_serial", None))
        self.label_2.setText(_translate("FreeIMUCal", "Accelerometer", None))
        self.label_3.setText(_translate("FreeIMUCal", "Magnetometer", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.uncalibratedTab), _translate("FreeIMUCal", "Uncalibrated", None))
        self.groupBox.setTitle(_translate("FreeIMUCal", "Accelerometer", None))
        self.label_14.setText(_translate("FreeIMUCal", "Offset X", None))
        self.label_15.setText(_translate("FreeIMUCal", "Offset Y", None))
        self.label_16.setText(_translate("FreeIMUCal", "Offset Z", None))
        self.label_17.setText(_translate("FreeIMUCal", "Scale X", None))
        self.label_18.setText(_translate("FreeIMUCal", "Scale Y", None))
        self.label_19.setText(_translate("FreeIMUCal", "Scale Z", None))
        self.groupBox_2.setTitle(_translate("FreeIMUCal", "Magnetometer", None))
        self.label_27.setText(_translate("FreeIMUCal", "Offset X", None))
        self.label_28.setText(_translate("FreeIMUCal", "Offset Y", None))
        self.label_29.setText(_translate("FreeIMUCal", "Offset Z", None))
        self.label_30.setText(_translate("FreeIMUCal", "Scale X", None))
        self.label_31.setText(_translate("FreeIMUCal", "Scale Y", None))
        self.label_32.setText(_translate("FreeIMUCal", "Scale Z", None))
        self.saveCalibrationEEPROMButton.setToolTip(_translate("FreeIMUCal", "Store the calibration parameters to the microcontroller EEPROM", None))
        self.saveCalibrationEEPROMButton.setText(_translate("FreeIMUCal", "Save to EEPROM", None))
        self.saveCalibrationHeaderButton.setToolTip(_translate("FreeIMUCal", "Store the calibration parameters in an header .h file. When such header is active the EEPROM calibration storage code is disabled thus saving program and data memory.", None))
        self.saveCalibrationHeaderButton.setText(_translate("FreeIMUCal", "Save to calibration.h", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab), _translate("FreeIMUCal", "Acc XY", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_4), _translate("FreeIMUCal", "Acc YZ", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_3), _translate("FreeIMUCal", "Acc ZX", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_7), _translate("FreeIMUCal", "Acc 3D", None))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_2), _translate("FreeIMUCal", "Magn XY", None))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_5), _translate("FreeIMUCal", "Magn YZ", None))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_6), _translate("FreeIMUCal", "Magn ZX", None))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_8), _translate("FreeIMUCal", "Magn 3D", None))
        self.clearCalibrationEEPROMButton.setToolTip(_translate("FreeIMUCal", "<html><head/><body><p>Clear any calibration parameter from the microcontroller EEPROM</p></body></html>", None))
        self.clearCalibrationEEPROMButton.setText(_translate("FreeIMUCal", "Clear EEPROM", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.calibratedTab), _translate("FreeIMUCal", "Calibrated", None))
        self.label_4.setText(_translate("FreeIMUCal", "To Be Implemented", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_9), _translate("FreeIMUCal", "Orientation Sensing Test", None))

from pyqtgraph import PlotWidget
from pyqtgraph.opengl import GLViewWidget
