
/**
 * FreeIMU calibration header. Automatically generated by FreeIMU_GUI.
 * Do not edit manually unless you know what you are doing.
*/


#define CALIBRATION_H

const int acc_off_x = -142;
const int acc_off_y = 384;
const int acc_off_z = 252;
const float acc_scale_x = 15899.095348;
const float acc_scale_y = 16657.942863;
const float acc_scale_z = 16527.518443;

const int magn_off_x = 342;
const int magn_off_y = 2663;
const int magn_off_z = -1277;
const float magn_scale_x = 3089.505519;
const float magn_scale_y = 3252.403513;
const float magn_scale_z = 2988.472267;
